# Generated by Django 3.1.2 on 2022-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='status',
            new_name='blog_status',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
