# Generated by Django 3.1.2 on 2022-01-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='messages',
        ),
    ]
