# Generated by Django 3.1.2 on 2022-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220125_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
