# Generated by Django 3.1.2 on 2022-04-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220417_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(max_length=255, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshots',
            field=models.ImageField(max_length=255, null=True, upload_to='images'),
        ),
    ]
