# Generated by Django 3.1.2 on 2022-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220417_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshots',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
