# Generated by Django 3.1.2 on 2022-04-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220417_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='', max_length=255, null=True)),
                ('blog_post', models.CharField(default='', max_length=1500, null=True)),
                ('paste_bin', models.ImageField(upload_to='images')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
