# Generated by Django 3.1.2 on 2022-04-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
