# Generated by Django 3.1.2 on 2022-05-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220503_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='id',
            new_name='blog_id',
        ),
    ]
