# Generated by Django 3.1.2 on 2022-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220511_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_slug',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
