# Generated by Django 3.1.2 on 2022-05-18 17:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_blogpost_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_post',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_slug',
            field=models.CharField(default=api.models.getSlug, max_length=8, unique=True),
        ),
    ]
