export const FooterData = [
    {
        title:'LinkedIn',
        icon:'',
        path:'https://www.linkedin.com/in/pavin-kiptoo-5250571aa/',
    },
    {
        title:'Instagram',
        icon:'',
        path:'https://www.instagram.com/__.hommie/',
    },
    {
        title:'Twitter',
        icon:'',
        path:'https://twitter.com/pavkiptoo',
    },
    {
        title:'Github',
        icon:'',
        path:'https://github.com/bl4ckh401/',
    },
]